import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Galileo",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // Default
    shortcut: "/favicon-16x16.png", // For high-resolution displays
    apple: "/favicon-apple.png", // For Apple devices
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
